### ISSUE TITLE
missing cmd.php file in example

### ISSUE THREAD

**Issue by seba1rx** [bekaku/php-thruway-web-socket-example#3]
In the description you mention a file that is missing:  App/cmd.php

There is no cmd.php in that directory.

I know it has been 3+ years since your last commit, but your example could be useful to anyone trying to learn the thruway library.

**Comment by bekaku** [comment]
in [root document]/cmd.php 

`php [root document]/cmd.php`

**Comment by seba1rx** [comment]
Wow thanks, I was only paying attention to the App directory and didn't look in the root directory!
